name: S3 Publish
permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  S3:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        id: creds
        with:
          aws-region: us-east-1
          output-credentials: true
          role-session-name: dai-shared
          role-to-assume: arn:aws:iam::996380035046:role/docs.digital.ai-996380035046-github-oidc-role
      - name: Add profile credentials to ~/.aws/credentials
        run: |
          aws configure set aws_access_key_id ${{ steps.creds.outputs.aws-access-key-id }} --profile dai-shared
          aws configure set aws_secret_access_key ${{ steps.creds.outputs.aws-secret-access-key }} --profile dai-shared
          aws configure set aws_session_token ${{ steps.creds.outputs.aws-session-token }} --profile dai-shared
          # The following serves as an example of how to interact with the S3 bucket.

      - name: Checkout docusaurus code
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Install Depedencies
        run: yarn install

      - name: Build Project
        run: |
          cd website
          yarn build

      - name: Sync with S3
        run: |
          cd ./website/build
          aws s3 sync teamforge s3://docs.digital.ai-996380035046/teamforge
